version: "3"

services:
  traefik:
    image: traefik:2.2
    networks:
      - web
      - internal
    volumes:
      - './traefik/conf/acme.json:/acme.json'
      - './traefik/conf/traefik.yml:/traefik.yml'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './traefik/certs:/certs'
    ports:
      - 80:80
      - 443:443
      - 9000:8080
    restart: always
    dns:
      - pihole
      - 1.1.1.1
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp"
    environment:
      TZ: 'Asia/Kolkata'
      WEBPASSWORD: ${WEBPASSWORD}
      PIHOLE_DNS_: ${PIHOLE_DNS_}
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    labels:
      - traefik.http.routers.pihole.rule=Host(`pihole.localhost`)
      - traefik.http.routers.pihole.tls=true
      - traefik.enable=true
      - traefik.port=80
    networks:
      - internal
      - web

  postgres:
    container_name: postgres
    image: postgres:13.4
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - './postgres-data/:/var/lib/postgresql/data'
    restart: always
    networks:
      - internal
    
  nocodb:
    container_name: nocodb
    image: nocodb/nocodb
    environment:
      NC_DB: pg://postgres:5432?u=${POSTGRES_USER}&p=${POSTGRES_PASSWORD}&d=${POSTGRES_USER}
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - "postgres"
    labels:
      - traefik.http.routers.nocodb.rule=Host(`nocodb.home.trieoflogs.com`)
      - traefik.http.routers.nocodb.tls=true
      - traefik.port=8080
      - traefik.enable=true
    networks:
      - internal
      - web

  joplin-server:
    container_name: joplin-server
    image: cvhariharan/joplin-server:v2.4.5-4-g0a54854f5
    environment:
      DB_CLIENT: pg
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: ${POSTGRES_USER}
      APP_PORT: 22300
      APP_BASE_URL: http://192.168.1.65:22300
    ports:
      - "22300:22300"
    depends_on:
      - "postgres"
    labels:
      - traefik.http.routers.joplin.rule=Host(`joplin.localhost`)
      - traefik.http.routers.joplin.tls=true
      - traefik.port=22300
      - traefik.enable=true
    restart: always
    networks:
      - internal
      - web
  
  etebase:
    container_name: etebase
    image: cvhariharan/etebase:v0.7.0-146-gd115040
    environment:
      APP_PORT: ${APP_PORT}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "5000:5000"
    volumes:
      - './etebase:/data'
    labels:
      - traefik.http.routers.etebase.rule=Host(`etebase.localhost`)
      - traefik.http.routers.etebase.tls=true
      - traefik.http.routers.etebase.tls.certresolver=lets-encrypt
      - traefik.port=5000
      - traefik.enable=true
    restart: unless-stopped
    networks:
      - internal
      - web

  dashy:
    container_name: dashy
    image: lissy93/dashy
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - './dashy:/app/public'
    labels:
      - traefik.http.routers.dashy.rule=Host(`dashy.localhost`)
      - traefik.http.routers.dashy.tls=true
      - traefik.http.routers.dashy.tls.certresolver=lets-encrypt
      - traefik.port=80
      - traefik.enable=true
    networks:
      - internal
      - web

networks:
  web:
    external: true
  internal:
    external: false
